version: '3.8'

services:
  backend1:
    build: ./backend1
    container_name: backend1
    ports:
      - "5001:5000"
    networks:
      - tokokita-net

  backend2:
    build: ./backend2
    container_name: backend2
    ports:
      - "5002:5000"
    networks:
      - tokokita-net

  nginx:
    build: ./nginx
    container_name: nginx-lb
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - tokokita-net

networks:
  tokokita-net:
    driver: bridge
